project:
  type: website
  output-dir: docs

website:
  title: "Website title"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - dash2.ipynb

format:
  html:
    theme: cosmo
    toc: true


