project:
  type: website
  output-dir: docs

website:
  title: "Website title"
  navbar:
    left:
      - about.qmd
      - href: dash_1.ipynb
        text: Dash 1
      - href: dash2.ipynb
        text: Dash 2
      - href: dash3.qmd
        text: Dash 3
      - href: dash4.qmd
        text: Dash 4

format:
  html:
    theme: 
      - litera
      - custom.scss
    toc: true


