[project]
authors = ["Maeve Murphy Quinlan <earmmu@leeds.ac.uk>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "quarto-tests"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
plotly = ">=5.24.1,<6"
numpy = ">=2.1.3,<3"
pandas = ">=2.2.3,<3"
jupyter = ">=1.1.1,<2"
